specify tag_fields as string
treasure-data/treasure-boxes pull request #282
Opened 2020-09-01 07:15 UTC by waysaku

Some Yahoo! DMP parameters could have number parameter as string like `0005`. In order to handle it as string explicitly, need to enclose with quotation.

2020-09-03 02:24 UTC, waysaku commented
If nobody has concern, I'll merge this PR in today 😉

2020-09-03 04:19 UTC, chezou commented
Change itself is ok, but I wonder if there's a way to set more realistic values for `****` things. At least, we should be able to set `td.database` with a specific name.

2020-09-04 09:18 UTC, waysaku commented
@chezou Thank you for reviewing. I'm afraid that I couldn't figure out what you mean. You mean we should show example values practically like following?
```
_export:
  td:
    database: user_db
```

2020-09-04 09:24 UTC, chezou commented
As you can see in other boxes, configuration shoulud be more specific one. For example, rss box sets td.database as `rss_db` 
https://github.com/treasure-data/treasure-boxes/blob/07a907cd3e567854e11522e84792dbd00236b59f/integration-box/rss/config/params.yml#L1-L3

In general, I think secrets variables should write as `${secret:some_secrets}` like https://github.com/treasure-data/treasure-boxes/blob/07a907cd3e567854e11522e84792dbd00236b59f/integration-box/pandas/pandas-df.dig#L13-L14, and variables like DB name should be set more concrete name.

2020-09-04 09:34 UTC, waysaku commented
@chezou ok. I got it. It looks good to change specific database name.
```
_export:
  td:
    database: sync_user_db
```

But the other things like entity_id, vendor_guid, etc.. depend on customer's one. Do you have any idea to set appropriate values which depend on customer's environment.

2020-09-04 10:06 UTC, chezou commented
I think there are two options:
1. Gather configurable variables into somewhere like `config/params.yml` with "REPLACE-ME" or something. Or, `config/params.yml.tmp` and ask to rename the file with filling actual values. I think this is clearer for customers about what they should set.
2. Make those variables secrets and enforce them to set secrets. This is a bit of abuse of secrets, and I don't think it's a good way though.

2020-09-04 10:44 UTC, waysaku commented
@chezou Thanks for your advice! I'll think about it carefully. Anyway can I merge this PR this time? because customer would refer this workflow.

2020-09-04 11:54 UTC, chezou requested changes
@waysaku At least, I would strongly recommend setting specific DB name as you described:
https://github.com/treasure-data/treasure-boxes/pull/282#issuecomment-687038210

2020-09-05 03:41 UTC, waysaku commented
@chezou Thanks for kindly advice! I added practical DB name and description for quotation. As for other parameters I'll improve as you pointed out when I need to update Yahoo Integration next time because a documentation which organize internally has distributed to current customers. Then I should update the document and this project in the same time. 
Anyway thank you again for your instructive advice.

2020-09-05 03:42 UTC, merged